# Generated by Django 3.0.7 on 2021-05-23 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shorturl', '0003_auto_20210522_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_url',
            name='currentuser',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
