# Generated by Django 3.0.7 on 2021-06-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0004_auto_20210524_0108'),
        ('shorturl', '0004_auto_20210522_0121'),
        ('shorturl', '0004_auto_20210524_0104'),
    ]

    operations = [
    ]
